import React from "react";

export const THEME = {
  light: {
    body: "#E2E2E2",
    toggleBorder: "#FFF",
    gradient: "linear-gradient(#39598A, #79D7ED)",

    text: "#2d302b",
    background: "#FAFAFA",
    backgroundGrey: "#F0F0F0",
    backgroundDarkGrey: "#BFBDBE",
    headerOrange: "#d6791f",
    paragraph: "#1d1d1d",
    headerGreen: "#5ab42c",
    white: "#fff",

    themePrimary: "#51967d",
    themeLighterAlt: "#f6fbf9",
    themeLighter: "#ddeee8",
    themeLight: "#c1e0d4",
    themeTertiary: "#8bc0ad",
    themeSecondary: "#61a38b",
    themeDarkAlt: "#498771",
    themeDark: "#3e725f",
    themeDarker: "#2d5446",
    neutralLighterAlt: "#f8f8f8",
    neutralLighter: "#f4f4f4",
    neutralLight: "#eaeaea",
    neutralQuaternaryAlt: "#dadada",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c8c8",
    neutralTertiary: "#c2c2c2",
    neutralSecondary: "#858585",
    neutralPrimaryAlt: "#4b4b4b",
    neutralPrimary: "#333",
    neutralDark: "#272727",
    black: "#1d1d1d",

    primaryBackground: "#fff",
    primaryText: "#333",
    bodyBackground: "#fff",
    bodyText: "#333",
    disabledBackground: "#f4f4f4",
    disabledText: "#c8c8c8",
  },
  dark: {
    body: "#363537",
    toggleBorder: "#6B8096",
    gradient: "linear-gradient(#091236, #1E215D)",

    text: "#FAFAFA",
    background: "#3b4039",
    backgroundGrey: "#868c83",
    backgroundDarkGrey: "#BFBDBE",
    headerOrange: "#d6791f",
    paragraph: "#fff",
    headerGreen: "#5ab42c",
    white: "#fff",

    themePrimary: "#38544a",
    themeLighterAlt: "#f5f8f7",
    themeLighter: "#d8e4df",
    themeLight: "#b8ccc5",
    themeTertiary: "#7a988e",
    themeSecondary: "#4a695e",
    themeDarkAlt: "#334c43",
    themeDark: "#2b4039",
    themeDarker: "#202f2a",
    neutralLighterAlt: "#f8f8f8",
    neutralLighter: "#f4f4f4",
    neutralLight: "#eaeaea",
    neutralQuaternaryAlt: "#dadada",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c8c8",
    neutralTertiary: "#c2c2c2",
    neutralSecondary: "#858585",
    neutralPrimaryAlt: "#4b4b4b",
    neutralPrimary: "#333",
    neutralDark: "#272727",
    black: "#1d1d1d",
    primaryBackground: "#fff",
    primaryText: "#333",
    bodyBackground: "#fff",
    bodyText: "#333",
    disabledBackground: "#f4f4f4",
    disabledText: "#c8c8c8",
  },
};

export const ThemeContext = React.createContext(THEME.light);
